[versions]
agp = "8.9.2"
foundation = "1.8.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"
appcompat = "1.7.0"
material = "1.12.0"
material3 = "1.3.2"
material3Version = "1.3.0"
recyclerview = "1.4.0"
constraintlayout = "2.2.1"
activityCompose = "1.9.2"
compose = "1.8.2" # Unified Compose version
navigationCompose = "2.8.0"
lifecycle = "2.9.0"
lifecycleViewmodelCompose = "2.9.1"
kotlinxCoroutinesAndroid = "1.9.0"
coilCompose = "2.7.0"
room = "2.7.1"
sqlite = "2.5.1"
camera = "1.4.2"
tensorflow-lite = "2.15.0"
tensorflow-lite-support = "0.4.3"
androidMail = "1.6.7"
javaxMail = "1.6.2"
jbcrypt = "0.4"
transportApi = "4.0.0"
junit = "4.13.2"
junitAndroid = "1.2.1"
espressoCore = "3.6.1"
google-fonts = "1.8.2"
uiTextGoogleFonts = "1.8.3"
uiVersion = "1.7.0"

[libraries]
android-activation = { module = "com.sun.mail:android-activation", version.ref = "androidMail" }
android-javamail = { module = "com.sun.mail:android-javamail", version.ref = "androidMail" }
android-mail = { module = "com.sun.mail:android-mail", version.ref = "androidMail" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-material3-v130 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "compose" }
androidx-ui-text-google-fonts-v183 = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "uiTextGoogleFonts" }
androidx-ui-v170 = { module = "androidx.compose.ui:ui", version.ref = "uiVersion" }
javax-mail = { module = "com.sun.mail:javax.mail", version.ref = "javaxMail" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidx-ui-tooling-preview-android = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "lifecycle" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "lifecycle" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-external-antlr = { module = "androidx.room:room-external-antlr", version.ref = "room" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "sqlite" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera" }
tensorflow-lite = { module = "org.tensorflow:tensorflow-lite", version.ref = "tensorflow-lite" }
tensorflow-lite-support = { module = "org.tensorflow:tensorflow-lite-support", version.ref = "tensorflow-lite-support" }
transport-api = { module = "com.google.android.datatransport:transport-api", version.ref = "transportApi" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitAndroid" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "google-fonts" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }